name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore:
      - 'release/**'
      - 'doc/**'

env:
  WORKING_DIRECTORY: backend

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod
          cache: true
          cache-dependency-path: |
            backend/go.sum
            backend/go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Lint Code
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ${{ env.WORKING_DIRECTORY }}
