name: Lint and Test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore:
      - 'release/**'
      - 'doc/**'

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
          cache-dependency-path: |
            ./go.sum
            ./go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh
          sudo mv ./bin/golangci-lint /usr/local/bin

      - name: Verify golangci-lint installation
        run: golangci-lint --version

      - name: Run golangci-lint
        run: golangci-lint

  test:
    name: Golang Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
          cache-dependency-path: |
            ./go.sum
            ./go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
